// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Todos$ReactTemplate = require("./Todos.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Todos$ReactTemplate.make(/* array */[])), "app");

/*  Not a pure module */
