// Generated by BUCKLESCRIPT VERSION 4.0.0, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Block = require("bs-platform/lib/js/block.js");
var React = require("react");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Todo$ReactTemplate = require("./Todo.bs.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

var component = ReasonReact.reducerComponent("Todos");

function make() {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              var lists = List.mapi((function (idx, todo) {
                      return ReasonReact.element(todo[/* title */0] + (" - " + String(idx)), undefined, Todo$ReactTemplate.make(todo[/* title */0], todo[/* isDone */1], /* array */[]));
                    }), self[/* state */1][/* todos */0]);
              return React.createElement("div", undefined, React.createElement("h1", undefined, "Todos"), $$Array.of_list(lists));
            }),
          /* initialState */(function () {
              return /* record */[/* todos : :: */[
                        /* record */[
                          /* title */"Mama mia",
                          /* isDone */false
                        ],
                        /* [] */0
                      ]];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              switch (action.tag | 0) {
                case 0 : 
                    return /* Update */Block.__(0, [/* record */[/* todos */List.append(state[/* todos */0], /* :: */[
                                      action[0],
                                      /* [] */0
                                    ])]]);
                case 1 : 
                    var todo = action[0];
                    var result = List.filter((function (x) {
                              return Caml_obj.caml_notequal(x, todo);
                            }))(state[/* todos */0]);
                    return /* Update */Block.__(0, [/* record */[/* todos */result]]);
                case 2 : 
                    throw [
                          Caml_builtin_exceptions.match_failure,
                          /* tuple */[
                            "Todos.re",
                            26,
                            29
                          ]
                        ];
                
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
